### ISSUE TITLE
Show lyric versions side by side

### ISSUE THREAD

**Issue by mazulo** [dunderlabs/pygalume#15]
Something like this:

| English version | Versão traduzida |
| --- | --- |
| Clipped wings, I was a broken thing | Asas cortadas, eu era algo partido |
| Had a voice, had a voice but I could not sing | Tinha uma voz mas não conseguia cantar |
| You'd worn me down | Você tinha me desgastado |
| I struggled on the ground | Eu lutei enquanto estava no chão |
| So lost, the line had been crossed | Tão perdida, havia passado do limite |
| Had a voice, had a voice but I could not talk | Tinha uma voz mas não conseguia falar |
| You held me down | Você me segurou |
| I struggle to fly now | Eu luto para voar agora |

**Comment by delete** [comment]
Would be good! 
I think would be good add an option, that let you choose to print side by side or not.

Something like this:

`pygalume -a "MyArtist" -m "HimSong"  -p`

`-p`(p as pretty) option for print side by side.

What do you think? Is `-p` a good flag?

**Comment by mazulo** [comment]
Yeah! I think that would be great. Some APIs use this flag to show the .json in a human-readable way.

**Comment by delete** [comment]
Finally close with PR #24 .
