### ISSUE TITLE
Definir Requisitos

### ISSUE THREAD

**Issue by mazulo** [dunderlabs/pygalume#2]
Aqui discutiremos sobre as features que farão parte do projeto, sendo cada uma explicada e aplicada através da demonstração de código (se possível).

**Comment by mazulo** [comment]
Listando as primeiras funções da API:
- `def getLyrics(self, artist, music)`: função responsável por realizar a busca de uma música, mediante os 2 argumentos fornecidos: `artist` e `music`, sendo este o nome do artista e o nome da música, respectivamente. Essa função deve levantar uma exceção customizada para os erros de: música não encontrada (`MusicNotFound`), e artista não encontrado (`ArtistNotFound`). A partir dela, poderá ser mandada dicas para o usuário para que cheque o nome digitado dos parâmetros.

Ao receber os parâmetros, o mesmo é tratado pelo método `formating_string_name()`, responsável por formatar a entrada para uma string válida para ser usada na API. Abaixo um exemplo prático do uso:

``` shel
>>> artist = 'David Guetta'
>>> formating_string_name(artist)
'david-guetta'
>>>
```

API também cobrirá muitas outras funções como: pesquisar por discografia, listar músicas, mostrar tradução, salvar letras localmente. Sendo cada uma dessas descritas em outros comentários, conforme o projeto for sendo desenvolvido.

**Comment by delete** [comment]
-`def getDiscography(artist)`: função responsável por buscar a lista dos álbuns de um artista, mediante ao argumento fornecido: `artist`, sendo este o nome do artista. Essa função deve levantar uma exceção customizada para o erro de: artista não encontrado (`ArtistNotFound`). A partir dela, poderá ser mandada dicas para o usuário para que cheque o nome digitado dos parâmetros.
