### ISSUE TITLE
optparse is deprecated

### ISSUE THREAD

**Issue by mazulo** [dunderlabs/pygalume#9]
The [optparse](https://docs.python.org/3/library/optparse.html) module is deprecated since version version 3.2 (in Python 3.x) and 2.7 (in Python 2.x). Instead we should use the relative module [argparse](https://docs.python.org/3/library/argparse.html#module-argparse).

I want to use the argparse in another project that I'm developing for a meetup. So after that I could do that in Pygalume too.

**Comment by delete** [comment]
O gosh, i didn't know. 
Is it deprecated before the PR #7 ?

If yes, i didn't notice.

**Comment by mazulo** [comment]
Apparently it's deprecated a [few years ago(http://stackoverflow.com/questions/3217673/why-use-argparse-rather-than-optparse). I figure out this when I was searching for tutorials that could explain more about it (optparse) to me.

**Comment by delete** [comment]
I got it. My bad!
Do you want to update or I do?
Em 22/11/2015 00:13, "Patrick Mazulo" notifications@github.com escreveu:

**Comment by mazulo** [comment]
If you do not mind, I will. That will be good, once I need to study this package hahaha

**Comment by delete** [comment]
hahaha it is fine! If you need some help, let me know!
